### ISSUE TITLE
Example consumer API

### ISSUE THREAD

**Issue by ilanbiala** [kifi/franz#49]
The consumer API using enumerators isn't completely intuitive, and it would be great to have an example in the README.

**Comment by ilanbiala** [comment]
@kifi @stkem Bump.

**Comment by stkem** [comment]
@ilanbiala I think what is really not completely intuitive here is enumerators/iteratees in general, since this is a pretty standard use case of those. To be perfectly honest, I've always found it hard to wrap my head around, but I don't think this is the right place for an explanation.
That being said, if you want to contribute a short example I'd be happy to include it. :-)
