### ISSUE TITLE
Consuming stops on first parsing error

### ISSUE THREAD

**Issue by gmalouf** [kifi/franz#68]
I'm seeing behavior where I receive a json message that my consumer did not expect and the parsing failure seems to stop the enumerator from consuming.

My assumption had been that the following will cause the enumerator to run indefinitely consuming until client is closed:

`s.enumeratorWithLock(20.seconds).run(i)`

What I realized is that run returns a future - from my tests this future completes on the first failure and the consuming appears to stop.  Seems to me the desired behavior would be to log an error but continue consuming from the queue...right?

This issue seems to have been brought up in 2014 but closed...[https://github.com/kifi/franz/issues/32](Issue 32)

**Comment by andrewconner** [comment]
Thanks for the feedback, Gary. This is actually behavior of Play's `Iteratee`s. While it may be a bit surprising that consuming stops, forcing specific logging (in effect, silently failing if a project uses something other than std out for exception handling) ends up being fairly opinionated. In addition to `Iteratee`s, `Future`s also rely on the consumer to handle errors rather than logging.

What we can do is update the documentation to be clear that this behavior occurs. For your case, you can wrap calls in a `Try` and log out the error case.

**Comment by gmalouf** [comment]
Understood Andrew.  It's just ugly if you want to restart consuming in the
event of a failure.  Using a try addresses the immediate issue.
